name: emulators
description: A utility library to automate mobile emulators. Wraps `xcrun` for iOS and the Android CLI tools.
version: 0.6.0
repository: https://github.com/tim-smart/dart_emulators.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  elemental: ^0.2.1
  freezed_annotation: any
  json_annotation: ^4.8.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^4.0.0
  freezed: any
  json_serializable: ^6.0.1
